import { useState } from "react";
import { ChevronLeft, ChevronRight, Crown, FileDown, FileText, Lock } from "lucide-react";
import {
  useClipperStore,
  fmtMoney,
  PAYMENT_METHOD_LABELS,
  CATEGORY_LABELS,
  SCHEDULE_C_LINES,
  type PaymentMethod,
  type ExpenseCategory,
  type IncomeEntry,
  type ExpenseEntry,
} from "@/lib/clipper-store";

function escapeCsv(v: string) {
  return `"${v.replace(/"/g, '""')}"`;
}

function downloadCsv(incomes: IncomeEntry[], expenses: ExpenseEntry[], year: number) {
  const rows = [["Type", "Date", "Amount", "Category / Method", "Note"]];
  incomes.forEach((e) =>
    rows.push([
      "Income",
      new Date(e.date).toLocaleDateString("en-US"),
      e.amount.toFixed(2),
      PAYMENT_METHOD_LABELS[e.paymentMethod],
      e.clientNote ?? "",
    ]),
  );
  expenses.forEach((e) =>
    rows.push([
      "Expense",
      new Date(e.date).toLocaleDateString("en-US"),
      e.amount.toFixed(2),
      CATEGORY_LABELS[e.category],
      e.description ?? "",
    ]),
  );
  const csv = rows.map((r) => r.map(escapeCsv).join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `clipper-records-${year}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

async function downloadScheduleCPdf(opts: {
  year: number;
  totalIn: number;
  totalOut: number;
  net: number;
  seTax: number;
  byCat: Map<ExpenseCategory, number>;
}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text(`Clipper — Schedule C Summary`, 14, 20);
  doc.setFontSize(11);
  doc.setTextColor(120);
  doc.text(`Tax year ${opts.year}`, 14, 27);
  doc.setTextColor(20);

  doc.setFontSize(12);
  let y = 40;
  const line = (label: string, value: string) => {
    doc.text(label, 14, y);
    doc.text(value, 196, y, { align: "right" });
    y += 8;
  };
  line("Gross income", fmtMoney(opts.totalIn));
  line("Total expenses", fmtMoney(opts.totalOut));
  line("Net profit", fmtMoney(opts.net));
  line("Estimated SE tax", fmtMoney(opts.seTax));

  y += 4;
  doc.setDrawColor(200);
  doc.line(14, y, 196, y);
  y += 10;

  doc.setFontSize(13);
  doc.text("Deductions by Schedule C line", 14, y);
  y += 8;
  doc.setFontSize(11);
  if (opts.byCat.size === 0) {
    doc.setTextColor(140);
    doc.text("No expenses logged.", 14, y);
    doc.setTextColor(20);
  }
  [...opts.byCat.entries()].forEach(([cat, amount]) => {
    doc.text(`${SCHEDULE_C_LINES[cat]} — ${CATEGORY_LABELS[cat]}`, 14, y);
    doc.text(fmtMoney(amount), 196, y, { align: "right" });
    y += 8;
  });

  y += 6;
  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(
    "Generated by Clipper. Verify figures with a licensed tax preparer before filing.",
    14,
    y,
  );

  doc.save(`clipper-schedule-c-${opts.year}.pdf`);
}

export function TaxesScreen({ onPremium }: { onPremium: (f?: string) => void }) {
  const [store] = useClipperStore();
  const isPremium = store.user?.isPremium;
  const currentYear = new Date().getFullYear();
  const earliestYear = [...store.incomeEntries, ...store.expenseEntries].reduce(
    (min, e) => Math.min(min, new Date(e.date).getFullYear()),
    currentYear,
  );
  const [year, setYear] = useState(currentYear);

  const incomes = store.incomeEntries.filter(
    (e) => e.confirmed && new Date(e.date).getFullYear() === year,
  );
  const expenses = store.expenseEntries.filter(
    (e) => !e.voided && new Date(e.date).getFullYear() === year,
  );
  const totalIn = incomes.reduce((s, e) => s + e.amount, 0);
  const totalOut = expenses.reduce((s, e) => s + e.amount, 0);
  const net = totalIn - totalOut;
  const seTax = Math.max(0, net * 0.9235 * 0.153);
  const tipsTotal = incomes.filter((e) => e.isTip).reduce((s, e) => s + e.amount, 0);
  const tipsDeduction = Math.min(tipsTotal, 25000);

  // by method
  const byMethod = new Map<PaymentMethod, number>();
  incomes.forEach((e) =>
    byMethod.set(e.paymentMethod, (byMethod.get(e.paymentMethod) ?? 0) + e.amount),
  );

  // by category
  const byCat = new Map<ExpenseCategory, number>();
  expenses.forEach((e) => byCat.set(e.category, (byCat.get(e.category) ?? 0) + e.amount));

  // Quarter dates
  const quarters = [
    { label: "Q1", date: new Date(year, 3, 15) },
    { label: "Q2", date: new Date(year, 5, 16) },
    { label: "Q3", date: new Date(year, 8, 15) },
    { label: "Q4", date: new Date(year + 1, 0, 15) },
  ];
  const now = new Date();
  const isCurrentYear = year === currentYear;
  const nextQ = isCurrentYear ? (quarters.find((q) => q.date >= now) ?? quarters[0]) : null;
  const daysToNextQ = nextQ ? Math.ceil((+nextQ.date - +now) / 86400000) : 0;

  const monthIsJan = isCurrentYear && now.getMonth() === 0;
  const canPrevYear = year > earliestYear;
  const canNextYear = year < currentYear;

  return (
    <div className="space-y-4 pb-24">
      <header className="pt-2">
        <div className="text-xs uppercase tracking-[0.22em] text-brass">Taxes</div>
        <h1 className="mt-1 font-display text-3xl">Year at a glance</h1>
      </header>

      <div className="card-luxe flex items-center justify-between p-3">
        <button
          onClick={() => setYear((y) => y - 1)}
          disabled={!canPrevYear}
          className="rounded-full p-2 hover:bg-accent disabled:opacity-30"
          aria-label="Previous year"
        >
          <ChevronLeft className="h-5 w-5" />
        </button>
        <div className="font-display text-xl">{year}</div>
        <button
          onClick={() => setYear((y) => y + 1)}
          disabled={!canNextYear}
          className="rounded-full p-2 hover:bg-accent disabled:opacity-30"
          aria-label="Next year"
        >
          <ChevronRight className="h-5 w-5" />
        </button>
      </div>

      {monthIsJan && (
        <button
          onClick={() => onPremium("Tax Season walkthrough")}
          className="card-luxe flex w-full items-center gap-3 border-brass/40 bg-gradient-to-r from-brass/10 to-transparent p-4 text-left"
        >
          <Crown className="h-5 w-5 text-brass" />
          <div className="flex-1">
            <div className="font-display text-lg">Tax season is here</div>
            <div className="text-xs text-muted-foreground">
              Reconcile 1099-Ks and prep your preparer packet
            </div>
          </div>
        </button>
      )}

      {/* Year summary */}
      <div className="card-luxe p-5">
        <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
          In Your Pocket · {isCurrentYear ? "YTD" : year}
        </div>
        <div className="mt-1 font-display text-4xl brass-text">{fmtMoney(net)}</div>
        <div className="mt-4 grid grid-cols-3 gap-3 border-t border-border/60 pt-4 text-center">
          <Stat label="Income" value={fmtMoney(totalIn)} tone="success" />
          <Stat label="Deductions" value={fmtMoney(totalOut)} tone="destructive" />
          <Stat label="SE tax est." value={fmtMoney(seTax)} />
        </div>
        <p className="mt-3 text-[10px] text-muted-foreground">
          SE tax = net × 0.9235 × 0.153. Half is deductible from AGI on Schedule 1.
        </p>
      </div>

      {tipsTotal > 0 && (
        <div className="card-luxe border-brass/30 p-4">
          <div className="text-[11px] uppercase tracking-[0.18em] text-brass">
            {year} Tips Deduction
          </div>
          <div className="mt-1.5 grid grid-cols-2 gap-3">
            <div>
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Tips logged
              </div>
              <div className="font-display text-xl">{fmtMoney(tipsTotal)}</div>
            </div>
            <div>
              <div className="text-[10px] uppercase tracking-widest text-muted-foreground">
                Potential deduction
              </div>
              <div className="font-display text-xl brass-text">{fmtMoney(tipsDeduction)}</div>
            </div>
          </div>
          <p className="mt-2 text-[10px] text-muted-foreground">
            Goes on Schedule 1-A — tell your preparer.
          </p>
        </div>
      )}

      {/* By method */}
      <div className="card-luxe p-4">
        <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
          Income by payment method
        </div>
        <div className="mt-3 space-y-2.5">
          {[...byMethod.entries()].length === 0 && (
            <div className="text-sm text-muted-foreground">No income logged yet</div>
          )}
          {[...byMethod.entries()].map(([m, v]) => {
            const pct = totalIn > 0 ? (v / totalIn) * 100 : 0;
            const note = METHOD_NOTES[m];
            return (
              <div key={m}>
                <div className="flex items-center justify-between text-sm">
                  <span className="font-medium">{PAYMENT_METHOD_LABELS[m]}</span>
                  <span className="font-display">{fmtMoney(v)}</span>
                </div>
                <div className="mt-1 h-1 rounded-full bg-muted">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-brass to-[oklch(0.5_0.15_148)]"
                    style={{ width: `${pct}%` }}
                  />
                </div>
                <div className="mt-1 text-[10px] text-muted-foreground">{note}</div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Quarter */}
      {nextQ && (
        <div className="card-luxe p-4">
          <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
            Next estimated payment
          </div>
          <div className="mt-1.5 flex items-end justify-between">
            <div>
              <div className="font-display text-2xl">
                {nextQ.label} ·{" "}
                {nextQ.date.toLocaleDateString("en-US", { month: "short", day: "numeric" })}
              </div>
              <div className="text-xs text-muted-foreground">
                {daysToNextQ} day{daysToNextQ !== 1 ? "s" : ""} away
              </div>
            </div>
            {daysToNextQ <= 14 && (
              <span className="rounded-full bg-warning/20 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-warning">
                Due soon
              </span>
            )}
          </div>
        </div>
      )}

      {/* Deductions by Schedule C line */}
      <div className="card-luxe p-4">
        <div className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">
          Deductions · Schedule C
        </div>
        <div className="mt-2 divide-y divide-border/60">
          {[...byCat.entries()].map(([c, v]) => (
            <div key={c} className="flex items-center justify-between py-2 text-sm">
              <span>{CATEGORY_LABELS[c]}</span>
              <span className="font-display">{fmtMoney(v)}</span>
            </div>
          ))}
          {[...byCat.entries()].length === 0 && (
            <div className="py-3 text-sm text-muted-foreground">No expenses yet</div>
          )}
        </div>
      </div>

      {/* Exports */}
      <div className="grid grid-cols-2 gap-2.5">
        <ExportBtn
          icon={<FileText className="h-4 w-4" />}
          label="Schedule C PDF"
          locked={!isPremium}
          onClick={() =>
            isPremium
              ? downloadScheduleCPdf({ year, totalIn, totalOut, net, seTax, byCat })
              : onPremium("Schedule C PDF export")
          }
        />
        <ExportBtn
          icon={<FileDown className="h-4 w-4" />}
          label="CSV records"
          onClick={() => downloadCsv(incomes, expenses, year)}
        />
      </div>
    </div>
  );
}

const METHOD_NOTES: Record<PaymentMethod, string> = {
  cashApp: "1099-K issued if >$20K AND >200 txns",
  venmo: "1099-K issued if >$20K AND >200 txns",
  zelle: "No 1099-K — still fully taxable",
  applePay: "Confirm 1099-K status with your bank",
  appleCash: "Confirm 1099-K status with your bank",
  cash: "No 1099-K — self-reported",
  other: "Verify with payer",
};

function Stat({
  label,
  value,
  tone,
}: {
  label: string;
  value: string;
  tone?: "success" | "destructive";
}) {
  return (
    <div>
      <div
        className={`font-display text-lg ${tone === "success" ? "text-success" : tone === "destructive" ? "text-destructive" : ""}`}
      >
        {value}
      </div>
      <div className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div>
    </div>
  );
}

function ExportBtn({
  icon,
  label,
  locked,
  onClick,
}: {
  icon: React.ReactNode;
  label: string;
  locked?: boolean;
  onClick: () => void;
}) {
  return (
    <button
      onClick={onClick}
      className={`card-luxe relative flex h-20 flex-col items-start justify-between p-3 text-left tap-highlight ${
        locked ? "opacity-95" : ""
      }`}
    >
      <div className="grid h-8 w-8 place-items-center rounded-full bg-brass/10 text-brass">
        {icon}
      </div>
      <div className="text-sm font-semibold">{label}</div>
      {locked && (
        <div className="absolute right-2 top-2 flex items-center gap-1 rounded-full bg-brass/15 px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wider text-brass">
          <Lock className="h-2.5 w-2.5" /> Premium
        </div>
      )}
    </button>
  );
}
